// LICENSE: GNU GPL v3 You should have received a copy of the GNU General
// Public License along with this program. If not, see
// https://www.gnu.org/licenses/.

/////////////////////// symbol-pocker.mjs ///////////////////////////////
// A UI widget for inserting symbols                                   //
/////////////////////////////////////////////////////////////////////////

const symbols = {
  " ": "non-breaking space",
  " ": "thin space",
  "-": "hyphen",
  "–": "en-dash",
  "—": "em-dash",
  "…": "ellipsis",
  "‘": "left single quote",
  "’": "right single quote/apostrophe",
  "“": "left double quote",
  "”": "right double quote",
  "ʹ": "prime",
  "ʺ": "double prime",
  "'": "straight single quote",
  "\"": "straight double quote",
  "†": "dagger",
  "‡": "double dagger",
  "•": "bullet",
  "§": "section",
  "¶": "paragraph",
  "¬": "negation",
  "∀": "for all",
  "∃": "exists",
  "∅": "null set",
  "∈": "membership",
  "∉": "non-membership",
  "∧": "conjunction",
  "∨": "disjunction",
  "∩": "intersection",
  "∪": "union",
  "∴": "therefore",
  "≅": "congruence",
  "≈": "similarity",
  "≠": "inequality",
  "≡": "equivalence",
  "⊂": "proper subset",
  "⊃": "proper superset/material implication",
  "⊆": "subset",
  "⊇": "superset",
  "⊢": "turnstile",
  "⊨": "double turnstile",
  "⊥": "absurdity",
  "✖": "splat x",
  "⊤": "triviality",
  "←": "left arrow",
  "↑": "up arrow",
  "→": "right arrow",
  "↓": "down arrow",
  "↔": "left right arrow",
  "↕": "up down arrow",
  "⇐": "left double arrow",
  "⇑": "up double arrow",
  "⇒": "right double arrow",
  "⇓": "down double arrow",
  "⇔": "left right double arrow",
  "⇕": "up down double arrow",
  "⌜": "left corner quote",
  "⌝": "right corner quote",
  "□": "box",
  "◇": "diamond",
  "⥽": "fishtail",
  "℩": "inverted iota",
  "ℵ": "aleph",
  "ℶ": "bet",
  "℘": "Weierstrass p",
  "−": "minus",
  "×": "multiply/times",
  "÷": "divided by",
  "≤": "less than or equal to",
  "≥": "greater than or equal to",
  "∑": "summation",
  "∏": "bounded product",
  "∫": "integral",
  "∂": "derivative",
  "∇": "difference",
  "√": "square root",
  "∞": "infinity",
  "±": "plus/minus",
  "½": "one half",
  "©": "copyright sign",
  "¡": "inverted exclamation",
  "¿": "inverted question mark",
  "¢": "cents",
  "£": "pounds",
  "€": "euro",
  "°": "degrees",
  "™": "trademark",
  "©": "copyright",
  "®": "registered",
  "‹": "left angle quotation mark",
  "›": "right angle quotation mark",
  "«": "left double angle quotation mark",
  "»": "right double angle quotation mark",
  "‚": "low single quotation mark",
  "„": "low double quotation mark",
  "⟨": "left angle bracket",
  "⟩": "right angle bracket",
  "ß": "Ess Zed",
  "À": "A grave accent",
  "Á": "A acute accent",
  "Â": "A circumflex",
  "Ã": "A tilde",
  "Ä": "A umlaut",
  "Å": "A ring",
  "Æ": "AE",
  "Ç": "C cedilla",
  "È": "E grave",
  "É": "E acute",
  "Ê": "E circumflex",
  "Ë": "E umlaut",
  "Ì": "I grave",
  "Í": "I acute",
  "Î": "I circumflex",
  "Ï": "I umlaut",
  "Ñ": "N tilde",
  "Ò": "O grave",
  "Ó": "O actue",
  "Ô": "O circumflex",
  "Õ": "O tilde",
  "Ö": "O umlaut",
  "Ø": "slashed O",
  "Ù": "U grave",
  "Ú": "U acute",
  "Û": "U circumflex",
  "Ü": "U umlaut",
  "Ý": "Y acute",
  "à": "a grave",
  "á": "a acute",
  "â": "a circumflex",
  "ã": "a tilde",
  "ä": "a umlaut",
  "å": "a ring",
  "æ": "ae",
  "ç": "c cedilla",
  "è": "e grave",
  "é": "e acute",
  "ê": "e circumflex",
  "ë": "e umlaut",
  "ì": "i grave",
  "í": "i acute",
  "î": "i circumflex",
  "ï": "i umlaut",
  "ñ": "n tilde",
  "ò": "o grave",
  "ó": "o acute",
  "ô": "o circumflex",
  "õ": "o tilde",
  "ö": "o umlaut",
  "ø": "slashed o",
  "ù": "u acute",
  "ú": "u grave",
  "û": "u circumflex",
  "ü": "u umlaut",
  "ý": "y acute",
  "𝔹": "double struck B",
  "ℂ": "double struck C",
  "ℍ": "double struck H",
  "𝕀": "double struck I",
  "ℕ": "double struck N",
  "ℙ": "double struck P",
  "ℚ": "double struck Q",
  "ℝ": "double struck R",
  "ℤ": "double struck Z",
  "Α": "Alpha",
  "Β": "Beta",
  "Γ": "Gamma",
  "Δ": "Delta",
  "Ε": "Epsilon",
  "Ζ": "Zeta",
  "Η": "Eta",
  "Θ": "Theta",
  "Ι": "Iota",
  "Κ": "Kappa",
  "Λ": "Lambda",
  "Μ": "Mu",
  "Ν": "Nu",
  "Ξ": "Xi",
  "Ο": "Omicron",
  "Π": "Pi",
  "Ρ": "Rho",
  "Σ": "Sigma",
  "Τ": "Tau",
  "Υ": "Upsilon",
  "Φ": "Phi",
  "Χ": "Chi",
  "Ψ": "Psi",
  "Ω": "Omega",
  "α": "alpha",
  "β": "beta",
  "γ": "gamma",
  "δ": "delta",
  "ε": "epsilon",
  "ζ": "zeta",
  "η": "eta",
  "θ": "theta",
  "ι": "iota",
  "κ": "kappa",
  "λ": "lambda",
  "μ": "mu",
  "ν": "nu",
  "ξ": "xi",
  "ο": "omicron",
  "π": "pi",
  "ρ": "rho",
  "ς": "final sigma",
  "σ": "sigma",
  "τ": "tau",
  "υ": "upsilon",
  "φ": "phi",
  "χ": "chi",
  "ψ": "psi",
  "ω": "omega",
  "ϑ": "theta variant",
  "ϕ": "phi variant",
  "𝒜": "script A",
  "ℬ": "script B",
  "𝒞": "script C",
  "𝒟": "script D",
  "ℰ": "script E",
  "ℱ": "script F",
  "𝒢": "script G",
  "ℋ": "script H",
  "ℐ": "script I",
  "𝒥": "script J",
  "𝒦": "script K",
  "ℒ": "script L",
  "ℳ": "script M",
  "𝒩": "script N",
  "𝒪": "script O",
  "𝒫": "script P",
  "𝒬": "script Q",
  "ℛ": "script R",
  "𝒮": "script S",
  "𝒯": "script T",
  "𝒰": "script U",
  "𝒱": "script V",
  "𝒲": "script W",
  "𝒳": "script X",
  "𝒴": "script Y",
  "𝒵": "script Z",
  "𝒶": "script a",
  "𝒷": "script b",
  "𝒸": "script c",
  "𝒹": "script d",
  "ℯ": "script e",
  "𝒻": "script f",
  "ℊ": "script g",
  "𝒽": "script h",
  "𝒾": "script i",
  "𝒿": "script j",
  "𝓀": "script k",
  "𝓁": "script l",
  "𝓂": "script m",
  "𝓃": "script n",
  "ℴ": "script o",
  "𝓅": "script p",
  "𝓆": "script q",
  "𝓇": "script r",
  "𝓈": "script s",
  "𝓉": "script t",
  "𝓊": "script u",
  "𝓋": "script v",
  "𝓌": "script w",
  "𝓍": "script x",
  "𝓎": "script y",
  "𝓏": "script z",
  "𝔄": "fraktur A",
  "𝔅": "fraktur B",
  "ℭ": "fraktur C",
  "𝔇": "fraktur D",
  "𝔈": "fraktur E",
  "𝔉": "fraktur F",
  "𝔊": "fraktur G",
  "ℌ": "fraktur H",
  "ℑ": "fraktur I",
  "𝔍": "fraktur J",
  "𝔎": "fraktur K",
  "𝔏": "fraktur L",
  "𝔐": "fraktur M",
  "𝔑": "fraktur N",
  "𝔒": "fraktur O",
  "𝔓": "fraktur P",
  "𝔔": "fraktur Q",
  "ℜ": "fraktur R",
  "𝔖": "fraktur S",
  "𝔗": "fraktur T",
  "𝔘": "fraktur U",
  "𝔙": "fraktur V",
  "𝔚": "fraktur W",
  "𝔛": "fraktur X",
  "𝔜": "fraktur Y",
  "ℨ": "fraktur Z",
  "𝔞": "fraktur a",
  "𝔟": "fraktur b",
  "𝔠": "fraktur c",
  "𝔡": "fraktur d",
  "𝔢": "fraktur e",
  "𝔣": "fraktur f",
  "𝔤": "fraktur g",
  "𝔥": "fraktur h",
  "𝔦": "fraktur i",
  "𝔧": "fraktur j",
  "𝔨": "fraktur k",
  "𝔩": "fraktur l",
  "𝔪": "fraktur m",
  "𝔫": "fraktur n",
  "𝔬": "fraktur o",
  "𝔭": "fraktur p",
  "𝔮": "fraktur q",
  "𝔯": "fraktur r",
  "𝔰": "fraktur s",
  "𝔱": "fraktur t",
  "𝔲": "fraktur u",
  "𝔳": "fraktur v",
  "𝔴": "fraktur w",
  "𝔵": "fraktur x",
  "𝔶": "fraktur y",
  "𝔷": "fraktur z",

}

export default function symbolPicker(callback) {
  const d = document.createElement("dialog");
  const a = document.createElement("article");
  a.classList.add('symbolpicker','pico');
  const ddiv = document.createElement("div");
  d.appendChild(a);
  a.appendChild(ddiv);
  let h = '';
  for (let c in symbols) {
    h += '<span title="' + symbols[c] + '">' + c + '</span>';
  }
  ddiv.innerHTML = h;
  const ss = ddiv.getElementsByTagName("span");
  for (const s of ss) {
    s.callback = callback;
    s.mydialog = d;
    s.onclick = function(){
      this.callback(this.innerHTML);
      this.mydialog.close();
    };
  }
  document.body.appendChild(d);
  d.showModal();
}
